let _ = "Mint DAU token 1000000";
let account1 = principal "u4f2v-igzyj-kgr2d-ipjf5-dnkz6-sl6mm-gxues-usbeb-2bthn-pfjdq-kae";
let account2 = principal "g27n3-ynszd-oh3rr-p3xnx-vuhl4-nufyt-xlbbw-x4fsg-5pbiv-jwbkk-7qe";
let dip20 = record { canister_id = principal "su63m-yyaaa-aaaaa-aaala-cai" };
let dip20Canister = principal "su63m-yyaaa-aaaaa-aaala-cai";
let dip721Canister = principal "st75y-vaaaa-aaaaa-aaalq-cai";
let ic = principal "aaaaa-aa";
let marketplace = record { canister_id = principal "tzq7c-xqaaa-aaaaa-aaamq-cai" };
let marketplaceCanister = principal "tzq7c-xqaaa-aaaaa-aaamq-cai";
let nftSc = record { canister_id = principal "st75y-vaaaa-aaaaa-aaalq-cai" };
let reserveCanister = principal "t6rzw-2iaaa-aaaaa-aaama-cai";
let reserveSc = record { canister_id = principal "t6rzw-2iaaa-aaaaa-aaama-cai" };
let resp = variant { Ok = 2 : nat };
